name: metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
permissions:
  contents: write
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people_types: followers
          plugin_people: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.signal-boost.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_starlists: yes
          plugin_starlists_only: signal-boost
          plugin_starlists_limit: 1
          plugin_starlists_limit_repositories: 100
          plugin_starlists_shuffle_repositories: no
          plugin_starlists_languages: yes
